-- ═══════════════════════════════════════════════════════════
--  CodeArena — Seed Data
-- ═══════════════════════════════════════════════════════════
USE codearena;

-- ─── Admin user (password: Admin@1234) ───────────────────
INSERT IGNORE INTO users (username, email, password_hash, role, bio, skills) VALUES
('admin', 'admin@codearena.io', '$2a$12$LQv3c1yqBwlVHPZU5zJa0OWo5VJfMG.CdVNXXJl6WCvxMt7VTN2Uu', 'admin', 'CodeArena platform administrator', 'Node.js,React,MySQL,DevOps');

-- ─── Hackathons ───────────────────────────────────────────
INSERT INTO hackathons
  (title, organizer, description, theme, mode, difficulty, prize_pool, prize_amount,
   registration_link, eligibility, rules, max_team_size, min_team_size,
   registration_end, hackathon_start, hackathon_end, tags, status, featured, created_by)
VALUES
(
  'HackIndia 2026',
  'HackIndia Foundation',
  'India''s largest student hackathon returns with an AI/ML track, Web3 challenges, and a sustainability track. Join 10,000+ students from 500+ colleges competing for ₹50 lakh in prizes.',
  'AI / ML',
  'hybrid',
  'open',
  '₹50,00,000',
  5000000,
  'https://hackindia.xyz',
  'Open to all college students and recent graduates (2025/2026 batch). Teams of 2-4.',
  'No plagiarism. Submissions must be original work built during the hackathon. Open source libraries allowed.',
  4, 2,
  '2026-05-15 23:59:00',
  '2026-05-20 09:00:00',
  '2026-05-22 18:00:00',
  'AI,ML,Web3,Sustainability,India',
  'upcoming',
  TRUE,
  1
),
(
  'Smart India Hackathon 2026',
  'Ministry of Education, Govt. of India',
  'Government problem statements across 17 categories including agriculture, health, finance, and smart cities. The premier national-level hackathon for Indian students.',
  'GovTech',
  'offline',
  'open',
  '₹1,00,000 per winner',
  100000,
  'https://sih.gov.in',
  'Open to all students enrolled in Indian colleges/universities.',
  'Teams must register via their college nodal centre. Software and hardware tracks available.',
  6, 2,
  '2026-06-30 23:59:00',
  '2026-08-01 09:00:00',
  '2026-08-02 18:00:00',
  'GovTech,Agriculture,Health,SmartCity',
  'upcoming',
  TRUE,
  1
),
(
  'BerkeleyAI Hack',
  'UC Berkeley AI Club',
  'A 36-hour hackathon focused on cutting-edge AI applications. Sponsors include Anthropic, OpenAI, and Google DeepMind. Build responsible AI applications that matter.',
  'Artificial Intelligence',
  'online',
  'advanced',
  '$25,000',
  25000,
  'https://berkeleyaihack.com',
  'Open worldwide. Individual or teams up to 4.',
  'Projects must use at least one AI/ML component. All code must be pushed to GitHub.',
  4, 1,
  '2026-05-01 23:59:00',
  '2026-05-10 12:00:00',
  '2026-05-12 12:00:00',
  'AI,LLM,MachineLearning,USA',
  'upcoming',
  TRUE,
  1
),
(
  'ETHIndia 2026',
  'Devfolio',
  'The world''s largest Ethereum hackathon is back in India. Build DeFi, NFT, DAO, and Layer 2 projects with Web3 superpowers. ₹1 crore+ in bounties from 30+ protocols.',
  'Web3 / Blockchain',
  'offline',
  'intermediate',
  '₹1,00,00,000+',
  10000000,
  'https://ethindia.co',
  'Open to all developers. Prior Solidity/Web3 knowledge preferred but not mandatory.',
  'Projects must be deployed on Ethereum or an EVM-compatible chain.',
  4, 1,
  '2026-07-20 23:59:00',
  '2026-08-15 10:00:00',
  '2026-08-17 18:00:00',
  'Web3,Ethereum,DeFi,NFT,Blockchain,India',
  'upcoming',
  FALSE,
  1
),
(
  'MLH Global Hack Week: AI',
  'Major League Hacking',
  'A week-long virtual event featuring daily workshops, challenges, and mini-hackathons all centered around Artificial Intelligence. Great for beginners!',
  'AI / ML',
  'online',
  'beginner',
  'Swag + MLH Fellowship fast-track',
  0,
  'https://mlh.io/seasons/2026/events',
  'Open to all students and recent grads worldwide.',
  'Participate in any or all daily challenges. Each challenge is judged separately.',
  4, 1,
  '2026-05-05 23:59:00',
  '2026-05-06 00:00:00',
  '2026-05-12 23:59:00',
  'AI,MLH,Beginner,Global',
  'upcoming',
  FALSE,
  1
),
(
  'Fintech Hackathon by Razorpay',
  'Razorpay',
  'Build the future of payments and financial services. Open banking, UPI 2.0 innovations, fraud detection, and financial inclusion are this year''s key tracks.',
  'FinTech',
  'hybrid',
  'intermediate',
  '₹15,00,000',
  1500000,
  'https://razorpay.com/hackathon',
  'Open to students and early-career professionals (0-2 years experience).',
  'Projects must integrate at least one Razorpay API. Top teams invited to Bangalore office.',
  3, 2,
  '2026-06-10 23:59:00',
  '2026-06-20 10:00:00',
  '2026-06-22 18:00:00',
  'FinTech,Payments,UPI,Banking,India',
  'upcoming',
  FALSE,
  1
),
(
  'NASA Space Apps Challenge',
  'NASA',
  'The world''s largest global hackathon. Use NASA''s open data to solve real-world challenges related to Earth, space exploration, and the universe.',
  'Space / Earth Science',
  'online',
  'open',
  'Global Nominee Recognition + NASA internship opportunities',
  0,
  'https://www.spaceappschallenge.org',
  'Open to everyone worldwide, any age.',
  'Use only NASA open data. Projects can be hardware, software, visualization, or storytelling.',
  6, 1,
  '2026-09-30 23:59:00',
  '2026-10-03 00:00:00',
  '2026-10-05 23:59:00',
  'NASA,Space,Earth,OpenData,Global',
  'upcoming',
  TRUE,
  1
),
(
  'HealthTech Hack by Apollo',
  'Apollo Hospitals & Google',
  'Reimagine healthcare with technology. Build solutions for telemedicine, diagnostics, patient monitoring, mental health, and accessibility.',
  'HealthTech',
  'hybrid',
  'open',
  '₹20,00,000',
  2000000,
  'https://apollohealthhack.com',
  'Open to students, developers, doctors, and designers.',
  'All submissions must consider patient privacy and data safety. Teams of 2-5.',
  5, 2,
  '2026-06-01 23:59:00',
  '2026-06-15 09:00:00',
  '2026-06-17 18:00:00',
  'HealthTech,AI,Telemedicine,MentalHealth',
  'upcoming',
  FALSE,
  1
),
(
  'CodeForGood — JPMorgan Chase',
  'JPMorgan Chase & Co.',
  'A 24-hour hackathon where you build tech solutions for non-profit organizations. Make a real difference while showcasing your skills for a chance at a PPO.',
  'Social Impact',
  'offline',
  'open',
  'Pre-placement offer opportunity + ₹5,00,000',
  500000,
  'https://careers.jpmorgan.com/codeforgood',
  'Open to final-year students and pre-final-year students from CS/IT/ECE streams.',
  'Select one non-profit organization from the provided list. Build to their brief.',
  4, 3,
  '2026-07-01 23:59:00',
  '2026-07-10 09:00:00',
  '2026-07-11 09:00:00',
  'SocialImpact,Finance,PPO,NonProfit',
  'upcoming',
  FALSE,
  1
),
(
  'Hack The North 2026',
  'University of Waterloo',
  'Canada''s biggest hackathon at University of Waterloo. 1,000 hackers from around the world, 36 hours, unlimited coffee, and incredible mentors from top tech companies.',
  'Open Innovation',
  'offline',
  'open',
  '$30,000 CAD',
  30000,
  'https://hackthenorth.com',
  'Open to students worldwide. Travel reimbursement available.',
  'No pre-built projects. All work must happen during the event. Hardware hacks welcome.',
  4, 1,
  '2026-08-15 23:59:00',
  '2026-09-12 18:00:00',
  '2026-09-14 12:00:00',
  'Canada,OpenTrack,Hardware,Software,Global',
  'upcoming',
  TRUE,
  1
),
(
  'Sustainability Hack 2026',
  'Microsoft & United Nations',
  'Build technology solutions addressing the 17 UN Sustainable Development Goals. Tracks include climate tech, clean energy, carbon footprint reduction, and green fintech.',
  'ClimaTech / Sustainability',
  'online',
  'open',
  '$50,000 USD',
  50000,
  'https://sustainabilityhack.microsoft.com',
  'Open worldwide to students, developers, NGOs, and social entrepreneurs.',
  'Projects must directly address at least one SDG. Open source preferred.',
  5, 1,
  '2026-05-20 23:59:00',
  '2026-06-01 00:00:00',
  '2026-06-03 23:59:00',
  'SDG,ClimaTech,GreenTech,Microsoft,UN',
  'upcoming',
  FALSE,
  1
),
(
  'DevFest Hack by Google',
  'Google Developer Groups India',
  'A nationwide hackathon run across GDG chapters. Build with Firebase, Flutter, Google Cloud, or Android. Local winners compete nationally.',
  'Google Technologies',
  'hybrid',
  'beginner',
  '₹10,00,000',
  1000000,
  'https://gdg.community.dev/devfest',
  'Open to students and developers of all levels.',
  'Must use at least one Google technology (Firebase, Google Cloud, Android, Flutter, etc.).',
  4, 1,
  '2026-10-15 23:59:00',
  '2026-11-01 09:00:00',
  '2026-11-02 18:00:00',
  'Google,Firebase,Flutter,Android,GDG,India',
  'upcoming',
  FALSE,
  1
);
